### ISSUE TITLE
LoggerF v2 to support Effectie v2

### ISSUE THREAD

**Issue by kevin-lee** [kevin-lee/logger-f#259]
# Task
## Summary
LoggerF v2 to support [Effectie v2](https://github.com/Kevin-Lee/effectie/issues/300)

## Project Details
Version:

## Description
- [x] Upgrade Effectie to v2 (#263)
- [x] Drop Scalaz Effect support (#265)
- [x] Move Log typeclass to core and keep the instances in the sub-projects (#266)
- [x] Add `F[A].log()` syntax and more to `logger-f-cats` (#272)
- [x] Redesign `LeveledMessage` (#278)
- [x] Add `ToLog[A]` type-class to support logging type `A` (#280)
- [x] ToLog type-class instance using cats.Show (#283)
- [x] Redesign `loggerf.core.syntax` and `loggerf.cats.syntax` (#285)
- [x] Add `ignoreA(A)` syntax (#307)
- [x] Upgrade effectie to `2.0.0-beta2` (#311)
- [x] Remove `logPure()` (#314)
- [x] Upgrade log libraries (#316)
- [x] Remove `effectie-syntax` from the `logger-f-core` project (#318)
- [x] Move `loggerf.cats.instances.logF` to `loggerf.instances.cats` (#321)
- [x] Change `loggerf.cats.syntax` to `loggerf.syntax` (#322)
- [x] `loggerf.cats.show` => `loggerf.instances.show` (#326)
- [x] `loggerf.future.instances.logFuture` => `loggerf.instances.future.logFuture` (#329)
- [x] Add `log_` returning `F[Unit]` (#355)
- [x] Add `logS(String)(String => LogMessage with NotIgnorable): F[String]` (#358)
- [x] Add `logS_(String)(String => LogMessage with NotIgnorable): F[Unit]` (#359)
