### ISSUE TITLE
Add log()(ignore) to skip logging

### ISSUE THREAD

**Issue by Kevin-Lee** [Kevin-Lee/logger-f#50]
# Task
## Summary 
Add `log(F[A])(ignore)`

## Project Details
Version: `0.1.0`

## Description
When you use `Either`, you probably don't want to log for a `Left` case or a `Right` case.
The same for `Option` as well. You may not want to log for a `None` case or `Some` case.
So LoggerF needs something like

```scala
// feab : F[Either[A, B]]
log(feab)(a => error(s"Error: $a"), ignore)
log(feab)(ignore, b => info(s"b: $b"))

// foa: F[Option[A]]
log(foa)(ifEmpty = error("It's empty!!!"), ignore)
log(foa)(ignore, a => info(s"a: $a"))
```
However, the following case should not be allowed.
```scala
// fa: F[A]
log(fa)(_ => ignore) // must be compile-time error
```

It would be nice to make the following case compile-time error but since `log()` is using currying it's not possible to have the second part overloading.
e.g.) Having `def log()(ignore, message)`, `def log()(message, ignore) `and def log()(message, message) together is not possible.
```
log(feab)(_ => ignore, _ => ignore) // compile-time error is desirable but not possible
```

- [ ] `ignore` for `Option`
- [ ] `ignore` for `Either`
- [ ] `ignore` for `OptionT`
- [ ] `ignore` for `EitherT`
